name: Harmon Test
on:
  issue_comment:
    types: [deleted]
    
permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  pulled_pork:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      ACTIONS_RUNNER_DEBUG: true
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - run: echo "Sorry, this level is not ready yet.... or is it?!"
